# Generated by Django 5.1 on 2024-08-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
